version: '3.8'

services:
  # VM 1: API Gateway & Product Service + Product DB Container
  vm1-product-db:
    image: mongo:6.0
    container_name: vm1-product-db
    ports:
      - "27017:27017"
    networks:
      - vms-net

  vm1-gateway-product:
    build: ./vm1-gateway-product
    container_name: vm1-gateway-product
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://vm1-product-db:27017/productDB
      - CART_SERVICE_URL=http://vm2-cart:5004
      - ORDER_SERVICE_URL=http://vm3-order:5003
    depends_on:
      - vm1-product-db
    networks:
      - vms-net

  # VM 2: Cart Service + Cart Redis DB Container
  vm2-cart-db:
    image: redis:7-alpine
    container_name: vm2-cart-db
    ports:
      - "6379:6379"
    networks:
      - vms-net

  vm2-cart:
    build: ./vm2-cart
    container_name: vm2-cart
    ports:
      - "5004:5004"
    environment:
      - PORT=5004
      - REDIS_HOST=vm2-cart-db
      - REDIS_PORT=6379
    depends_on:
      - vm2-cart-db
    networks:
      - vms-net

  # VM 3: Order Service + Order DB Container
  vm3-order-db:
    image: mongo:6.0
    container_name: vm3-order-db
    ports:
      - "27018:27017"
    networks:
      - vms-net

  vm3-order:
    build: ./vm3-order
    container_name: vm3-order
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - MONGO_URI=mongodb://vm3-order-db:27017/orderDB
      - PAYMENT_SERVICE_URL=http://vm4-payment:5005/api/payments
      - PRODUCT_SYNC_URL=http://vm1-gateway-product:5001/api/products/sync-stock
      - CART_SYNC_URL=http://vm2-cart:5004/api/cart/clear
    depends_on:
      - vm3-order-db
      - vm4-payment
    networks:
      - vms-net

  # VM 4: Payment Service + Payment DB Container
  vm4-payment-db:
    image: mongo:6.0
    container_name: vm4-payment-db
    ports:
      - "27019:27017"
    networks:
      - vms-net

  vm4-payment:
    build: ./vm4-payment
    container_name: vm4-payment
    ports:
      - "5005:5005"
    environment:
      - PORT=5005
      - MONGO_URI=mongodb://vm4-payment-db:27017/paymentDB
    depends_on:
      - vm4-payment-db
    networks:
      - vms-net

networks:
  vms-net:
    driver: bridge
