version: '3.8'

services:
  # 🌐 VM 1: API Gateway & Product Service + 1 Mongo DB Container (NoSQL)
  vm1-product-db:
    image: mongo:6.0
    container_name: vm1-product-db
    ports:
      - "27017:27017"
    networks:
      - vms-net

  vm1-gateway-product:
    build: ./vm1-gateway-product
    container_name: vm1-gateway-product
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://vm1-product-db:27017/productDB
      - CART_SERVICE_URL=http://vm2-cart:5004
      - ORDER_SERVICE_URL=http://vm3-order:5003
    depends_on:
      - vm1-product-db
    networks:
      - vms-net

  # 🛒 VM 2: Cart Service + 1st SQL DB Container (MySQL)
  vm2-cart-sql-db:
    image: mysql:8.0
    container_name: vm2-cart-sql-db
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_DATABASE: cart_sqldb
    ports:
      - "3306:3306"
    networks:
      - vms-net

  vm2-cart:
    build: ./vm2-cart
    container_name: vm2-cart
    ports:
      - "5004:5004"
    environment:
      - PORT=5004
      - DB_HOST=vm2-cart-sql-db
      - DB_USER=root
      - DB_PASSWORD=secretpassword
      - DB_NAME=cart_sqldb
    depends_on:
      - vm2-cart-sql-db
    networks:
      - vms-net

  # 📦 VM 3: Order Service + 2nd SQL DB Container (MySQL)
  vm3-order-sql-db:
    image: mysql:8.0
    container_name: vm3-order-sql-db
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_DATABASE: order_sqldb
    ports:
      - "3307:3306"
    networks:
      - vms-net

  vm3-order:
    build: ./vm3-order
    container_name: vm3-order
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - DB_HOST=vm3-order-sql-db
      - DB_USER=root
      - DB_PASSWORD=secretpassword
      - DB_NAME=order_sqldb
      - PAYMENT_SERVICE_URL=http://vm4-payment:5005/api/payments
      - PRODUCT_SYNC_URL=http://vm1-gateway-product:5001/api/products/sync-stock
      - CART_SYNC_URL=http://vm2-cart:5004/api/cart/clear
    depends_on:
      - vm3-order-sql-db
      - vm4-payment
    networks:
      - vms-net

  # 💳 VM 4: Payment Service + 3rd SQL DB Container (MySQL)
  vm4-payment-sql-db:
    image: mysql:8.0
    container_name: vm4-payment-sql-db
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_DATABASE: payment_sqldb
    ports:
      - "3308:3306"
    networks:
      - vms-net

  vm4-payment:
    build: ./vm4-payment
    container_name: vm4-payment
    ports:
      - "5005:5005"
    environment:
      - PORT=5005
      - DB_HOST=vm4-payment-sql-db
      - DB_USER=root
      - DB_PASSWORD=secretpassword
      - DB_NAME=payment_sqldb
    depends_on:
      - vm4-payment-sql-db
    networks:
      - vms-net

networks:
  vms-net:
    driver: bridge
