version: '3.8'

services:
  # Container 1: Dedicated Order SQL Database (MySQL 8.0 Docker Image)
  order-sql-db:
    image: mysql:8.0
    container_name: vm3-order-sql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_DATABASE: order_sqldb
    ports:
      - "3306:3306"
    volumes:
      - order-sql-db-data:/var/lib/mysql

  # Container 2: Order Microservice (Private VM - 10.128.0.9)
  order-service:
    build: .
    container_name: vm3-order-service
    restart: always
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - DB_HOST=order-sql-db
      - DB_USER=root
      - DB_PASSWORD=secretpassword
      - DB_NAME=order_sqldb
      - PAYMENT_SERVICE_URL=http://10.128.0.10:5005/api/payments
      - PRODUCT_SYNC_URL=http://10.128.0.7:5001/api/products/sync-stock
      - CART_SYNC_URL=http://10.128.0.8:5004/api/cart/clear
    depends_on:
      - order-sql-db

volumes:
  order-sql-db-data:
